version: "3.9"

services:
  db:
    image: postgres:15
    container_name: task-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - task-network  

  backend:
    build:
      context: ./backend
    container_name: task-backend
    ports:
      - "5000:5000"
    depends_on:
      - db

    networks:
       - task-network

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/taskdb
    restart: always

    command: ["./wait-for-it.sh","db:5432","--","python","app.py"]

  frontend:
    build:
      context: ./frontend
    container_name: task-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - task-network  

volumes:
  postgres_data:

networks:
   task-network:
      driver: bridge
